<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExperimentalControlPlatform.Core\ExperimentalControlPlatform.Core.csproj" />
    <ProjectReference Include="..\ExperimentalControlPlatform.Runtime\ExperimentalControlPlatform.Runtime.csproj" />
    <ProjectReference Include="..\ExperimentalControlPlatform.Devices\ExperimentalControlPlatform.Devices.csproj" />
  </ItemGroup>

</Project>
