<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>ExperimentalControlPlatform.Devices</RootNamespace>
    <AssemblyName>ExperimentalControlPlatform.Devices</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExperimentalControlPlatform.Core\ExperimentalControlPlatform.Core.csproj" />
  </ItemGroup>
</Project>
